tmux-python/libtmux

- libtmux/common.py
Update to saltstack's latest `salt.util.which`.
See also: https://redd.it/4laeut
> Update which() to use os.environ['PATH']

- libtmux/window.py
- tests/test_server.py
- tests/test_window.py
Added a `session` argument to `Window.move_window`, and supplied a default empty string argument to the `destination` arg.
This allows you to pass a session ID to `Window.move_window`, which will cause the window to change sessions.
I've also updated the tests to include explicit coverage for `Window.move_window` (with and without session moving) and `Server.new_session`.
> support moving windows to other sessions

- libtmux/pane.py
- libtmux/window.py
- tests/test_window.py
`vertical` parameter for `split_window()`, defaulting to True
> allow splitting panes horizontally

- libtmux/common.py
> Use `logger` instead of `logging`

- libtmux/pane.py
- libtmux/server.py
- libtmux/session.py
- libtmux/window.py
This allows specifying start_directory for creation of both
session and panes.
Clarifies some docstrings as well.
> Add start_directory to support to new sessions and panes

- README.rst
attached_window is a property, should not use function call.
> fix an error in readme

- libtmux/common.py
- tests/test_common.py
is_version('something') fails with installed tmux 1.9a
To allow tony/tmuxp#197 ;-)
> Fix error when using is_version with lettered tmux version

- libtmux/common.py
- tests/test_common.py
When the latest tmux is installed, `tmux -V` returns 'tmux master',
which wasn't properly handled by has_required_tmux_version().
Closes tony/tmuxp#199
> Fix has_required_tmux_version when latest tmux HEAD is installed

- libtmux/window.py
- tests/test_window.py
Fixes https://github.com/tony/tmuxp/issues/239
With the below in tmux config:
setw -g pane-border-format " #P "
Before the fix:
('pane-border-format', '"', '#P', '"')
After the fix:
('pane-border-format', ' #P ')
> Retain spaces in quoted strings in window options

- .travis.yml
- libtmux/session.py
- tests/test_session.py
> Add session id to Session cmds, when appropriate 

- libtmux/_compat.py
When tmux window title contains invalid utf-8 sequence, libtmux throws exception, for example:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 9: invalid start byte
```
This can be archieved with accidentaly cating binary data to stdout or with
```
$ printf '\033k;\x96\033\'
```
This issue seems to be fixed in tmux (https://github.com/tmux/tmux/commit/8149bc3fa6e93cb083b165a21baa5ec07dd473dc) - title is set only if it is valid utf-8.
Could we fix this issue by ignoring invalid utf-8 sequences directly in function **console_to_str**?
> console_to_str: ignore invalid utf-8

- libtmux/server.py
- libtmux/window.py
- tests/test_server.py
- tests/test_window.py
Make it possible to pass window_name and shell command to
server.new_session
Make it possible to pass shell command to window.split_window
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
> Add options for shell command

- libtmux/pane.py
Useful for displaying messages in a tmux session and doing stuff like:
```python
>>> pane.display_message('#T', get_text=True)
'server.py (~/Downloads/libtmux/libtmux) - NVIM'
```
Here is a complete example:
```python
>>> import libtmux
>>> server = libtmux.Server()
>>> session = server.list_sessions()[0]
>>> pane = session.attached_pane
>>> pane.display_message('Hallo World!')
>>> pane.display_message('#T', get_text=True)
['server.py (~/Downloads/libtmux/libtmux) - NVIM']
> Add method `display_message` to `Pane`

- libtmux/pane.py
This new method `Pane.capture_pane` will be very handy for capturing text from a tmux pane.
```python
>>> pane.capture_pane()
['lots and...',
'..lots of..',
'.cute text.']
```
So kawaii. :D
> Add method `capture_pane` to`Pane`

- libtmux/_compat.py
- libtmux/common.py
- tests/test_common.py
Before this PR, if a command was passed into `tmux_command` that had unicode characters in it, such as in the name of a session, format string, or window, a unicode error would be thrown when tmuxp was run with Python 2. The provided unit test shows an example failing test case of this behavior—the real-world use-case is `config.yml` files for tmuxp that contain unicode characters in their names.
This PR resolves the issue by using a python-version-independent conversion inside the `tmux_command` constructor (instead of `str`), assuming that unicode data being sent in Python 2 is encoded as `utf_8`, which is consistent with other places in the code that assumption is made.
Happy to answer any questions, an thanks for making this!
> Fix for unicode commands in Python 2

- libtmux/common.py
- tests/test_common.py
tmuxp currently crashes when used with
tmux next-2.9 (the latest Homebrew release).
```
TypeError: '<' not supported between instances of 'str' and 'int'
```
This patch avoids the error by making `get_version()`
strip the "next-" part of the version.
closes tmux-python/tmuxp#449
> Handle next-X.Y versions

- Pipfile
- Pipfile.lock
- requirements/test.txt
- setup.py
Remove old remnants of setup.py test
> Update pytest packages, setup.py infrastructure

- libtmux/_compat.py
- libtmux/common.py
> Fix deprecation warning when using collection.MutableMapping

- .github/workflows/tests.yml
- Caching for poetry
- Python 2.7
- Skip running internal PR matrixes twice (hopefully)
> CI: Add poetry caching from libvcs, add python 2.7

- CHANGES
- libtmux/common.py
- libtmux/pane.py
> Fix deprecation warnings due to invalid escape sequences.

- .github/workflows/tests.yml
See also: https://github.com/tmux-python/tmuxp/pull/633
> ci: Add tmux 3.0a (instead of 3.0) and 3.1 (3.1b)

- CHANGES
- libtmux/pane.py
- libtmux/window.py
While spliting window tmux supports '-p' to specify the amount (in
percentage) that the newly created pane will occupy with respect to
current pane. So let's expose the same functionality by an extra
argument percent to split_window function.
Signed-off-by: Jinank Jain <jinankj@amazon.de>
> Add percent arg to split window

- CHANGES
- libtmux/common.py
Needed for interact with big buffer.
Thanks to communicate method ~implemented with python > 3.~
~I don't know how to deal with it with python2 ?~
https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen.communicate
#251
Official docs:
Warning
Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS   pipe buffers filling up and blocking the child process.
> Better interaction with subprocess std[in|out|err]

- CHANGES
- libtmux/session.py
Previosly select_window() would not work in nested tmux scenarios, as
there was no tmux session ID in the final tmux command. This is because
select_window() already adds the '-t' argument, hence the check in
cmd() does not add the session ID.
Thanks to Fabian Lesniak and Andreas Fried for pointing this out.
Fixes #161
> Fix select_window() by providing the session ID as argument to -t

- libtmux/server.py
Technically this is a breaking change. Previously one could expect to detect that only **one** client is attached to the sessions via this property.
However, since previously `Server.attached_sessions` was broken (see #180 and PR to fix #341) I do not expect anybody to use the property currently.
Builds on https://github.com/tmux-python/libtmux/pull/341/files (<- Merge first)
> Remove attached sessions limitation to not detect multiple attached clients

- .github/workflows/publish-docs.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- .tool-versions
- README.md
- poetry.lock
- pyproject.toml
- requirements/dev.txt
- setup.py
- poetry 1.1.7 -> 1.1.12, use new installer
- Drop python 3.6
- Add python 3.10
- CI: test 3.7 and 3.10 (low and high end of supported releases)
- Update myst-parser and sphinx-autodoc-typehints
- Add `.pre-commit-config.yaml`
- black: update 21.9b0 -> 21.12b0
> CI, version, deprecation, precommit updates

- libtmux/server.py
- libtmux/session.py
- libtmux/window.py
Several APIs in libtmux fail with Tmux 3.1 installed but worked with Tmux 3.0/3.0a.
It appears that the format string used by the library to communicate with Tmux will ignore tabs and return lowercases instead. I switch the tab to a wildcard (e.g. `$@$`) but this could be any kind of string assuming it's sufficiently rare to not collide with desired user input.
> split on a special wildcard instead of tab

- docs/conf.py
- libtmux/_compat.py
- libtmux/common.py
- libtmux/exc.py
- libtmux/pane.py
- libtmux/server.py
- libtmux/session.py
- libtmux/test.py
- libtmux/window.py
- tests/conftest.py
- tests/test_common.py
```
pip install pyupgrade autoflake; \
pyupgrade --py37 tests/**/*.py docs/**/*.py libtmux/**/*.py; \
poetry run autoflake tests/**/*.py docs/**/*.py libtmux/**/*.py -i --ignore-init-module-imports; \
make black isort
```
> pyupgrade @ 3.7

- libtmux/_compat.py
- libtmux/common.py
Adding simple type hints in independent functions as a first step to introduce type hints to the project
> Adding unobtrusive type hinting

- libtmux/common.py
- libtmux/pane.py
- libtmux/server.py
- libtmux/session.py
- libtmux/window.py
* Adding `SessionDict`, `WindowDict`, and `PaneDict` type aliases to `common.py` for _list methods
* Adding hints for methods returning `self` and collections of children
> Adding type hints to class methods returning self and child

- libtmux/_compat.py
- libtmux/common.py
- libtmux/pane.py
- libtmux/session.py
- libtmux/window.py
* Fixed incorrectly indented `return True` line in `by` filter method in `_info` class methods
* Created intermediate filtered list variables for `_info` class methods to more explicitly define the return type
* Reduced nesting of `if` statements within class `attached` methods
* Removed redundant `int` casts
* Moved `MutableMapping` import statement from `_compat` to `common`
> Refactor: Cleaning up 

- CHANGES
- docs/api.md
- libtmux/exc.py
- libtmux/test.py
- tests/test_test.py
Previous implementation is equivalent to `return True`. This implementation, while API incompatible, is easy to use (I would modify the corresponding code in tmuxp myself) and enforces the timeout via an exception, which would help debugging since it provide the specific cause.
API docs updated accordingly. Environment variable preserved.
fixes #368 and addresses https://github.com/tmux-python/tmuxp/issues/704#issuecomment-1128288348 , it would also help with https://github.com/tmux-python/tmuxp/issues/620
> Modify retry() to take a callable and enforce the timeout

- libtmux/session.py
- tests/test_server.py
- tests/test_session.py
- tests/test_tmuxobject.py
- tests/test_window.py
Cherry-picked from #383 Import improvements
> Import tweaks

- .github/workflows/tests.yml
- CHANGES
- libtmux/common.py
- tests/test_common.py
- CI: Add tmux 3.3a to test suite
- Set `TMUX_MAX_VERSION`: 2.4 -> 3.3
> Update `TMUX_MAX_VERSION`, add 3.3a to CI

- CHANGES
- libtmux/pane.py
- libtmux/server.py
- libtmux/session.py
- libtmux/window.py
e.g. `Pane.{window,session,server}`, `Window.{session,server}`, `Session.server`
> Core relational typings: `Server`, `Session`, `Window`, `Pane`

- CHANGES
- libtmux/common.py
- libtmux/session.py
- libtmux/window.py
- tests/test_server.py
- tests/test_session.py
- tests/test_window.py
Via #389 
- Removed key lookups from {meth}`libtmux.common.EnvironmentMixin.show_environment`
Only `EnvironmentMixin.show_environment()` (without an argument) exists, and
it still returns a `dict`.
- Add key lookups via {meth}`libtmux.common.EnvironmentMixin.getenv`
```python
server.show_environment('DISPLAY')
server.getenv('DISPLAY')
session.show_environment('DISPLAY')
session.getenv('DISPLAY')
```
- Removed key lookups from {meth}`Session.show_options`
```python
session.show_options()  # still returns dict, without an argument
session.show_options('DISPLAY')
session.show_option('DISPLAY')
```
- Removed key lookups from {meth}`Window.show_window_options`
```python
window.show_window_options()  # still returns dict, without an argument
window.show_window_options('DISPLAY') …
```
> API Changes - Simplify `EnvironmentMixin`

- CHANGES
- libtmux/test.py
This function didn't work, see #368
> chore!(test): Remove retry(), deprecated in 0.13

- libtmux/common.py
- tests/test_tmuxobject.py
More after #383
- refactor(common): Generic improvements for TmuxRelationalObject
> More typing improvements

- CHANGES
- libtmux/pane.py
Before: `Pane.send_keys(cmd:str, suppress_history=False)`
Now: `Pane.send_keys(cmd:str, suppress_history=True)`
> refactor!(`Pane.send_keys`): Default `suppress_history` value to `False`

- .github/workflows/docs.yml
- .github/workflows/tests.yml
See if [recent changes](https://github.com/actions/setup-python/blob/v4/docs/advanced-usage.md#:~:text=Caching%20poetry%20dependencies%3A) / fixes to poetry caching simplify our flow.
This was originally added in https://github.com/vcs-python/libvcs/pull/316 but retracted due to https://github.com/actions/setup-python/issues/374. In recent versions this python version issue has apparently been fixed.
See also: https://github.com/tmux-python/tmuxp/pull/797, https://github.com/vcs-python/libvcs/pull/394, https://github.com/vcs-python/vcspull/pull/377
> ci(setup-python): Use v3/v4's caching method

- libtmux/server.py
- tests/test_server.py
> chore: Server.new_session: Create session w/o name

- libtmux/server.py
- tests/test_server.py
Avoid passing `-s session_name` when no `session_name` passed
Follow up to #400 for #399
> fix(Server.session_name): Handle empty session names better

- CHANGES
- libtmux/common.py
- libtmux/session.py
- tests/test_pane.py
Close #402
Seems the branch v0.8x did not exist anymore to backport this change.
> fix(tmux_cmd): remove only trailing new lines in stdout

- CHANGES
- libtmux/common.py
- libtmux/conftest.py
- tests/test_common.py
Follow-up of https://github.com/tmux-python/libtmux/issues/396#issuecomment-1221582103
Copy @mdeguzis
> fix(tmux_cmd): use shutil.which and only PATH to discover tmux

- .github/workflows/tests.yml
- CHANGES
- Makefile
- README.md
- docs/conf.py
- docs/internals/test.md
- docs/pytest-plugin.md
- docs/reference/common.md
- docs/reference/exceptions.md
- docs/reference/panes.md
- docs/reference/servers.md
- docs/reference/sessions.md
- docs/reference/windows.md
- poetry.lock
- pyproject.toml
- setup.cfg
Add gp-libs ([github](https://github.com/git-pull/gp-libs), [site](https://gp-libs.git-pull.com/), [PyPI](https://pypi.org/project/gp-libs/))
- Render changelog in [linkify_issues](https://gp-libs.git-pull.com/linkify_issues/)
- Fix Table of contents rendering with sphinx autodoc with [sphinx_toctree_autodoc_fix](https://gp-libs.git-pull.com/sphinx_toctree_autodoc_fix/)
> Add `gp-libs`: Test docs via doctest, table of contents for `sphinx.ext.autodoc`, change issues module

- CHANGES
- tests/conftest.py
- tests/test_pytest_plugin.py
For testing pytest plugin
Fixes #422
> tests(conftest): Add pytester plugin

- CHANGES
- conftest.py
- src/libtmux/conftest.py
- src/libtmux/pytest_plugin.py
> pytest plugin examples

- CHANGES
- pyproject.toml
- tests/test_common.py
- tests/test_pytest_plugin.py
Fixes (#441)
Avoid using internal pytest APIs for typing:
> fix(`pytest_plugin`): `Pytester` import, use public APIs from pytest

- CHANGES
- tests/test_pane.py
This makes the test fail (at least for me) as it still won't start bash but my login-shell (which is not bash).
> fix(test_capture_pane): use of double `env`

- CHANGES
- src/libtmux/common.py
- tests/test_pane.py
> test(test_capture_pane): Remove bashism(s)

- CHANGES
- src/libtmux/session.py
- src/libtmux/window.py
- tests/test_session.py
- tests/test_window.py
This is required for implementing https://github.com/tmux-python/tmuxp/issues/832.
> Feature: allow setting up custom environment when creating windows and/or panes

- CHANGES
- setup.cfg
- src/libtmux/_compat.py
- src/libtmux/common.py
- tests/test_common.py
- tests/test_version.py
`distutils` is deprecation `Version`
The new version will no longer select tmux versions like `3.1` vs `3.1a` vs `3.1b`.
We will backport `LegacyVersion` in a typesafe way to tmuxp.
> Replacement for `distutils.version.LooseVersion`, fix warning

- CHANGES
- src/libtmux/_compat.py
- src/libtmux/_vendor/_structures.py
- src/libtmux/_vendor/version.py
This package is too critical to pin, yet we rely on a derivitive of it from `distutils` to check versions for both python packages and `tmux(1)`.
For now, we'll vendorize it - though we don't necessarily pin it at the standard library version. 
In the future we'll write our own version comparator that's lighter.
See also https://github.com/tmux-python/libtmux/issues/364#issuecomment-1346511606
> Vendorize `Version`

- CHANGES
- src/libtmux/server.py
- tests/test_server.py
> Server: Behavior when no server exists

- src/libtmux/pane.py
- tests/test_pane.py
> feat(pane): add capability to use [-SE] flags to capture_pane

- CHANGES
- src/libtmux/window.py
This causes builder to break
https://github.com/tmux-python/tmuxp/issues/860
> fix(Window.set_window_option): Remove .refresh()

- CHANGES
- docs/pytest-plugin/index.md
- src/libtmux/pytest_plugin.py
> feat(pytest_plugin): Add `session_params`

- CHANGES
- src/libtmux/formats.py
See also https://github.com/tmux-python/libtmux/issues/472 and issue https://github.com/tmux-python/libtmux/issues/471 and PR https://github.com/tmux-python/libtmux/pull/473 from @hongwen000
> `FORMAT_SEPARATOR`: Change to a character less likely to collide with buffers
